root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main.exe ./cmd/server"
  bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "test", "data", "uploads", "pkg"]
  include_dir = []
  exclude_file = []
  delay = 1000
  stop_on_error = true
  send_interrupt = false
  kill_delay = 0

[log]
  time = true
  main_only = false
  color = true

[misc]
  clean_on_exit = false
